name: dartcli
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  process_run: ^0.12.3+2
  args: ^2.3.1
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  dcli: ^1.9.6
  yaml: ^3.1.0




